name = "chat-udia-ca"
compatibility_date = "2021-11-20"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
# command = "yarn && yarn test && yarn build"
command = "yarn && yarn build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ChatRoom" },
  { name = "LIMITERS", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]
